### PR TITLE
Precompiled header support for faster builds.

### PR DESCRIPTION
**Pull request by SyrianBallaS**
This is only for the dll, it doesn't affect the emulators.

### CODE REVIEW

**Comment by SyrianBallaS** [comment]
I'm temporarily using Windows 10 SDK to run code analysis, currently there are about 657 code defects. I'll make sure it'll work the XP target.

**Comment by RetroAchievements** [comment]
Hey dude, just to clarify, you want to change thousands of lines of code because a code analysis tool you picked told you to?

**Comment by RetroAchievements** [comment]
A huge proportion of these changes are you adding spaces etc and reformatting files. If we don't have the same formatting rules, aren't my changes just going to auto-format with visual studio back the way they were?

**Comment by SyrianBallaS** [comment]
Seems this works a bit differently than BitBucket, I didn't intended for the second commit to be part of this pull request because there's a few runtime errors I need to sort-out with the file streams. I greatly apologize for that and respect your concerns.

Well here's my explanation:

Sorry, I'll turn off CodeMaid. I don't know what your auto formatting rules because it's application dependent and there isn't any kind of editor configuration to use. Maybe we make an .editorconfig (or .codemaidconfig if you want to use CodeMaid it helps formatting XML) file so the formatting is consistent. The formatting I used was the default for C++ in Visual Studio. Formatting is not a big deal for me, w/e convention you want I'll follow.

The code analysis is from Microsoft's implementation of the C++ Core Guidelines. Microsoft made MSVC/VC++ so I'd assume they'd know how their API is supposed to be used. I reviewed all of the API violations on MSDN and ISO and they all seem legit. 

If you're using VS 2017, code analysis I used is built in. Just go to code analysis in the Project Properties and go to extensions, it follows the industry standard set by ISO (lead by Bjarne Stroustrup the creator of C++). If you want to learn more visit the <a href="http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines" >C++ Core Guidelines</a>.

The first commit does not include the code analysis adjustment, it merely minimizes the headers included and put them in a precompiled header for a near instantaneous build of the dll.

**Comment by SyrianBallaS** [comment]
Yeah there's some serious bugs that don't make any sense when checking for the latest toolset version (been testing RANes). I'll go into more detail later, it's kinda late.

**Comment by SyrianBallaS** [comment]
I'm gonna close this. When I'm ready, I'm gonna ask for help testing on RA. Currently working on "develop" branch on my repo. Then probably will do a pull request if everything turns out alright.

**Pull request closed without merging**
