### PR TITLE
RAIntegration only

### PR DESCRIPTION
**Pull request by meleu**
This PR makes this repo have `RA_Integration` code only.

I've tested the consistency here by cloning the repo:
```
git clone --depth 1 --branch raintegration_only --recursive https://github.com/RetroAchievements/RASuite
```

and then simply opening the `RA_Integration.sln` on Visual Studio and Ctrl+Shift+B to build it. It compiles just fine (many thanks to @Jamiras for helping on this matter).

Now an announcement similar to that one I made on our discord server (#developer-news channel):

---

In order to make things more organized (and maybe more welcoming for possible new contributors) we are going to make some changes on the RASuite code repository:

1. The current RASuite repo is going to be renamed to `RAIntegration` and will have only the code related to `RA_Integration` itself.

2. I've forked the current `RASuite` and named the forked repo as `RAEmus`. I didn't change anything yet, but soon it will reference this `RAIntegration` repo as a submodule. You already can see the repo here: <https://github.com/RetroAchievements/RAEmus>

3. Now we have a dedicated repo for `RALibretro`. Soon it will reference this `RAIntegration` repo as a submodule. You already can see the repo here: <https://github.com/RetroAchievements/RALibretro>

**Note**: on the RAWeb issue tracker we have some references to issues on RASuite repo. These references will **NOT** be affected! :wink:

### CODE REVIEW

**Comment by Jamiras** [comment]
`+325 −3,458,389`
Personally, I'd prefer to have the subdirectory moved into a separate repository (possibly as described here: https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/), so when a user clones or forks the repository they only get the RA_Integration code instead of the 3.5 millions lines we just put in the attic.

As for the changes, I can confirm that the project does build and appears to be functioning. The massive purge makes it impossible to actually review the changes here. Here's the subset of changes that followed the initial purge: https://github.com/RetroAchievements/RASuite/compare/39fde9fa010f83c427fb30c8325042efc2c5a7b3...raintegration_only

Note that MakeBuildVer.bat will have to be modified once we merge back to master. It's currently hard-coded for the latest version because it couldn't find the tags from the branch.

**Comment by meleu** [comment]
> I'd prefer to have the subdirectory moved into a separate repository (possibly as described here: https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/)

This method wipes out all commits history and entries on the issue tracker. The issues can be reopened, sure. But I would like to avoid losing all the commits history.

Personally I never touched the RA_Integration code, but I think others who worked on it possibly would have an unpleasant surprise if they need/want to check a previous commit.

I faced this scenario several times when contributing with RetroArch. "I want to implement FooBar, and I remember I made something similar on a previous commit. Let me check that commit's diff to get some inspiration."


> when a user clones or forks the repository they only get the RA_Integration code instead of the 3.5 millions lines we just put in the attic.

The solution for this is to clone the repo using `--depth N` where `N` is the number of commits you want to keep track on your clone. I usually clone with `--depth 1` when I don't care about all the previous commits on my clone.

**Comment by Jamiras** [comment]
It's the `--depth 1` that was confusing MakeBuildVer.bat. With a full clone, the "temporary" change I had to introduce was no longer necessary.

MakeBuildVer.bat finds the most recent tag matching "RAIntegration.*" to determine the last released version. Without previous commits, it can't find it.

**Comment by Jamiras** [comment]
>This method wipes out all commits history and entries on the issue tracker. The issues can be reopened, sure. But I would like to avoid losing all the commits history.

I agree that history is important, but the page indicates it will be maintained:

> If you create a new clone of the repository, you won't lose any of your Git history or changes when you split a folder into a separate repository.

**Comment by meleu** [comment]
@Jamiras my man!!! I'm holding myself to not run naked around the streets screaming **EUREKA!**

The `git filter-branch` command seems to be the cleanest way to go (not necessarily creating another repo, though). I'm diving into it right now. ;)

**Pull request closed without merging**
