### PR TITLE
RANES mismatch fixes, narrowing convention needed fix, unsigned int cast fix

### PR DESCRIPTION
**Pull request by loopyd**
more bugfixes from LupineDream:

- unsgined/singed long long literal problem fix in internally built rom database.  please be sure to use ULL instead of LL to prevent this error.
-  improper use of size_t in xstring across 32 and 64 bit arch into an always fixed struct (unsigned int declared).  it was unclear why size_t was used here, but it was fixed, as there is only ever a win32 build target, and a static unsigned int in the struct, size_t is unnecessary.
- debugger sign truncation protection (yet another few mismatches), a few sprintf statements where malformed, resulting in potentially incorrect output in the debugger from large unsigned integers outputting as signed ones.  a minor bug but worth the fix.

### CODE REVIEW

**Comment by ScottFromDerby** [comment]
Hey :) are these changes for gd specifically? Or for the RA repo?

**Comment by ScottFromDerby** [comment]
I don't think gd has had anything to do with ines-bad.h? Maybe I'm missing something?

**Comment by SyrianBallaS** [comment]
@loopyd
The width of size_t depends on the platform you are building, if x86 it's 4 bytes if x86_64/AMD64 it's 8 bytes. It can be implementation specific but that's how it usually is.

**Comment by loopyd** [comment]
GD was helping me Scott, it was a figure of speech sorry.

SyrianBallaS yes that is what I am refering to, that is why I fixed it.

**Comment by SyrianBallaS** [comment]
Cool, that sounds good to me.

**Comment by meleu** [comment]
Hi @loopyd ,

We're going to move all emulators code to [RAEmus repository](https://github.com/RetroAchievements/RAEmus). Could you submit a PR to that repo instead of here?

This repo here will have RA_Integration code only.

I'm closing this PR.

**Pull request closed without merging**
